# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cf50e45b76d0704c79f7c04ea35411031bc3f1b989ddd7c78b46cc2682d6bf950682a50d77ac886913371430b77494273d941b7b256d7922c5728a3c85e7f7a

test:
  secret_key_base: d2baae6be7e7e8c7dbf07eec9f08ee2c8fbe6b51796a83321bde3b350b26324b3d7c3105eb96e3aa17badc40b047dbb5d91671b7ae0ea67a348d20e78047865d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
